[build-system]
requires = ["setuptools>=62.6"]
build-backend = "setuptools.build_meta"

[project]
name = "xact"
description = "A mortality viewer"
dynamic = ["version"]
authors = [{ name = "John Koestner", email = "johnkoestner@outlook.com" }]
readme = 'README.md'
license = { file = 'LICENSE.md' }
requires-python = '>=3.9'

dependencies = [
    "arrow>=1.3.0",
    "black>=23.12.1",
    "dash>=2.15.0",
    "dask>=2024.2.0",
    "dask-expr>=0.4.1",
    "graphviz>=0.20.1",                 # only for lightgbm
    "isort>=5.13.2",
    "jupyterlab>=4.0.10",
    "jupyterlab-code-formatter>=2.2.1",
    "lightgbm>=4.3.0",                  # only for lightgbm
    "numpy>=1.24.4",
    "pandas>=2.0.3",
    "plotly>=5.18.0",
    "pyarrow>=14.0.2",
    "ruff>=0.1.11",
    "scikit-learn>=1.4",
    "seaborn>=0.13.2",
    "statsmodels>=0.14.1",
]

[project.urls]
homepage = "https://github.com/jkoestner/xact"
repository = "https://github.com/jkoestner/xact"

# TODO: Remove after setuptools support is dropped.
[tool.setuptools]
include-package-data = true # include files from MANIFEST.in

[tool.setuptools.packages.find]
exclude = ["tests*"]

[tool.setuptools.dynamic]
version = { attr = "xact.version.version" }


[tool.ruff]
line-length = 88
fix = false
unfixable = []
extend-include = ["*.ipynb"]

select = [
    # pyflakes
    "F",
    # pycodestyle
    "E",
    "W",
    # isort
    "I",
    # pydocstyle
    "D",
    # flake8-2020
    "YTT",
    # flake8-bugbear
    "B",
    # flake8-quotes
    "Q",
    # flake8-debugger
    "T10",
    # flake8-gettext
    "INT",
    # pylint
    "PL",
    # misc lints
    "PIE",
    # flake8-pyi
    "PYI",
    # tidy imports
    "TID",
    # implicit string concatenation
    "ISC",
    # type-checking imports
    "TCH",
    # comprehensions
    "C4",
    # pygrep-hooks
    "PGH",
    # Ruff-specific rules
    "RUF",
    # flake8-bandit: exec-builtin
    "S102",
    # numpy-legacy-random
    "NPY002",
    # Perflint
    "PERF",
    # flynt
    "FLY",
    # flake8-logging-format
    "G",
]

ignore = [
    ### Intentionally disabled
    # logging statement uses f-string
    "G004",
    # ignore __init__ docstring
    "D107",
    # these are conflicting errors
    "D203",
    "D212",
    # ignore == False vs is False due to pandas series
    "E712",
    "ISC001",
    # ruff too many branches and too many statements
    "PLR0912",
    "PLR0915",
]

[tool.ruff.lint]
exclude = ["*.ipynb"]
pylint.max-args = 10
